const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shrits',
      image: '/images/d1', // 679px * 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality pant from Nike',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shrits',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality shirt from Adidas',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-shirt',
      category: 'Pants',
      image: '/images/p3.jpeg',
      price: 252,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality shirt from Nike',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality pant from Puma',
    },
  ],
};
export default data;
